### ISSUE TITLE
Unable to edit tooltip on color can we have a toggle for hiding tooltip.

### ISSUE THREAD

**Issue by tarunchaudhry** [RSSchermer/ember-spectrum-color-picker#24]

**Comment by RSSchermer** [comment]
This addon is just a thin wrapper around [spectrum.js](https://github.com/bgrins/spectrum): it generates the HTML, which I assume includes the tooltip. As far as I can tell it does not offer an option to turn that off, unfortunately. I may be overlooking something of course, if I did please let me know, but otherwise this is probably not something this addon can really address.

**Comment by tarunchaudhry** [comment]
Fixed it using CSS by making the pointer event of element none.
